#!/usr/bin/zsh

# requirements
# - pacman: zsh-theme-powerlevel10k

ZSH="$HOME/.oh-my-zsh"
DISABLE_AUTO_UPDATE=true
HYPHEN_INSENSITIVE="true"

# zsh history (man zshoptions)
SAVEHIST=1000000
HISTSIZE=1200000
setopt share_history extended_history append_history hist_no_store hist_ignore_all_dups hist_expire_dups_first hist_ignore_space

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git colored-man-pages dircycle sudo archlinux systemd pip pass tmux vagrant docker)


# Set name of the theme to load. Look in ~/.oh-my-zsh/themes/
if [[ $(tty) == "/dev/tty"* ]]; then
    # tty
    ZSH_THEME="af-magic"
elif [[ -f "/usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme" ]]; then
    # daily use
    source "/usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme"
    POWERLEVEL9K_DISABLE_RPROMPT=true
    POWERLEVEL9K_STATUS_HIDE_SIGNAME="true"
    POWERLEVEL9K_STATUS_OK="false"
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh root_indicator status dir background_jobs virtualenv vcs command_execution_time)
    export VIRTUAL_ENV_DISABLE_PROMPT=1

    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    fi
else
    # daily use (if powerlevel10k is not available)
    ZSH_THEME="gallifrey"
fi


source "$ZSH/oh-my-zsh.sh"
source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
# files below must be sourced after $ZSH/oh-my-zsh.sh
if [[ -f "$HOME/.bash_env" ]]; then source "$HOME/.bash_env"; fi
if [[ -f "$HOME/.bash_aliases" ]]; then source "$HOME/.bash_aliases"; fi
if [[ -f "$HOME/.zshrc_local" ]]; then source "$HOME/.zshrc_local"; fi
if (type fzf && (type fd || type find)) &>/dev/null; then
    source "/usr/share/fzf/key-bindings.zsh"
    source "/usr/share/fzf/completion.zsh"
    source "${DOTFILES}/fzf/fzf-source"
fi
