#!/usr/bin/bash
# vi: ft=bash

# requirements: fzf, pass, bash, gpg-connect-agent, fd/find, grep, sed, gnu coreutils, xargs, xdotool
# helpful reads:
# - https://demu.red/blog/2016/06/how-to-check-if-your-gpg-key-is-in-cache/

set -euo pipefail
shopt -s extglob


# global variables
ENABLE_PREVIEW="${ENABLE_PREVIEW:-0}"
GPG_KEY_ID="${GPG_KEY_ID:-}"


function password_files {
    export PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR:-$HOME/.password-store/}"
    export PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR%%+(/)}/"
    cd "$PASSWORD_STORE_DIR"

    if type fd &>/dev/null; then
        fd --type f --hidden --no-ignore --extension 'gpg' | sed 's|.gpg||'
    elif type find &>/dev/null; then
        find "$HOME/.password-store" -type f -iname '*\.gpg' | sed "s|$PASSWORD_STORE_DIR||; s|.gpg||"
    else
        # reset the gpg key id to (implicitly) disable the preview
        GPG_KEY_ID=
        printf "Please install 'fd' or 'find'\\n"
    fi
}

function fuzzy {
    export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:- --no-height --exit-0 --extended --cycle --reverse}"
    export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --bind change:top"

    if [[ "$ENABLE_PREVIEW" == "1" ]] && [[ -n "$GPG_KEY_ID" ]] && gpg-connect-agent "keyinfo $GPG_KEY_ID" '/bye' | grep ' 1 P ' &>/dev/null; then
    FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS}"
        fzf --bind F12:toggle-preview --preview 'pass show {}'
    else
        fzf
    fi
}

function main {
    if (( $# > 0 )); then
        if [[ "${1}" == "--preview" ]]; then
            ENABLE_PREVIEW="1"
        fi
    fi

    passfile=$(password_files | fuzzy)
    nohup xargs -r pass show --clip=1 &>/dev/null <<< "$passfile" &
    xdotool search --onlyvisible --pid $$ windowclose &>/dev/null
}


main "$@"
